Add secret check step to first-pipeline.yml
Added a step to check for the presence of a secret in the pipeline.

diff --git a/.github/workflows/first-pipeline.yml b/.github/workflows/first-pipeline.yml
--- a/.github/workflows/first-pipeline.yml
+++ b/.github/workflows/first-pipeline.yml
@@ -21,3 +21,12 @@ jobs:
             echo "index.html missing! Pipeline failing."
             exit 1
           fi
+      - name: Use secret safely
+        run: |
+          if [ -z "${{ secrets.MY_SECRET }}" ]; then
+            echo "Secret is missing"
+            exit 1
+          else
+            echo "Secret is available and securely loaded"
+          fi
+
